---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client:
      ansible_host: 54.162.145.120
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "C:/Users/jlmpa/Desktop/EAZY_TRAINING/AWS-Keys/OpenSSH.pem"

